[package]
name = "game_engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "opengl_wrapper"
path = "src/lib.rs"

[[bin]]
name = "game_engine"
path = "src/main.rs"

[dependencies]

[build-dependencies]
cc = "1"