[package]
name = "rust_test_game"
version = "0.1.0"
edition = "2024"

[dependencies]
game_engine = { path = "../game_engine" }
reqwest = { version = "0", features = ["blocking"] }
serde = "1"
serde_json = "1"
crossbeam-channel = "0"
log ="0"
fern = "0"
chrono = "0"